---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-nfs-protonmail-bridge-data
spec:
  storageClassName: "freenas-nfs-manual-csi"
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4
    - nolock
    - noatime
  csi:
    driver: org.democratic-csi.node-manual
    readOnly: false
    fsType: nfs
    volumeHandle: pv-nfs-protonmail-bridge-data
    volumeAttributes:
      server: storage-server-lagg.lan
      share: /mnt/r01_1tb/k8s/protonmail-bridge-data
      node_attach_driver: nfs
      provisioner_driver: node-manual

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-protonmail-bridge-data
  namespace: tools
  annotations:
    volume.beta.kubernetes.io/storage-class: "freenas-nfs-manual-csi"
spec:
  storageClassName: freenas-nfs-manual-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  volumeName: pv-nfs-protonmail-bridge-data

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: protonmail-bridge
  namespace: tools
  labels:
    app: protonmail-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protonmail-bridge
  template:
    metadata:
      labels:
        app: protonmail-bridge
    spec:
      containers:
        - name: protonmail-bridge-container
          image: shenxn/protonmail-bridge:2.3.0-1
          resources: {}
          ports:
            - containerPort: 25
          volumeMounts:
            - mountPath: "/root/"
              name: protonmail-data
      volumes:
        - name: protonmail-data
          persistentVolumeClaim:
            claimName: pvc-nfs-protonmail-bridge-data

---
apiVersion: v1
kind: Service
metadata:
  name: protonmail-bridge-smtp
  namespace: tools
  labels:
    app: protonmail-bridge
spec:
  selector:
    app: protonmail-bridge
  type: ClusterIP
  ports:
    - name: smtp
      port: 25
      targetPort: 25
